services:
    db:
        image: mysql:8
        container_name: my_blog_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: blog_db
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        ports:
            - '3306:3306'
        volumes:
            - myblog-data:/var/lib/mysql
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    myblog-data:
